jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Install webapp
      run: git clone -b dev https://github.com/axelor/open-suite-webapp.git open-suite-webapp
    - continue-on-error: true
      name: move to the right place
      run: mkdir -p open-suite-webapp/modules/axelor-open-suite && ls | grep -v open-suite-webapp
        | xargs -I{} mv {} open-suite-webapp/modules/axelor-open-suite
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x open-suite-webapp/gradlew
    - continue-on-error: true
      name: Check spotless format with gradle task
      run: cd open-suite-webapp && ./gradlew spotlessCheck
    - continue-on-error: true
      name: Check that CSV files use the correct CR/LF EOL char (\r\n)
      run: cd open-suite-webapp && ./gradlew checkCsvEOL
    - continue-on-error: true
      name: Check that rptdesign files do not have credentials
      run: cd open-suite-webapp && ./gradlew checkBirtCredentials
    - continue-on-error: true
      name: Check changelog generation with gradle task
      run: cd open-suite-webapp && ./gradlew generateChangelog
    - continue-on-error: true
      name: Check XML files validity
      run: cd open-suite-webapp && ./gradlew checkXml
    - continue-on-error: true
      name: Build without tests
      run: cd open-suite-webapp && ./gradlew -xtest clean build
    - continue-on-error: true
      name: Run tests
      run: cd open-suite-webapp && ./gradlew test
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
